version: "2"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - prologue-sync:/var/www/app:nocopy
    ports:
      - "3000:3000"
      - "3035:3035"
      - "8080:8080"
    tty: true
    depends_on:
      - "db"
      - "redis"
    links:
      - db
      - redis
    environment:
      PG_USERNAME: development
      PG_PASSWORD: "GdS)FP6*B7zJ"
      REDIS_URL: redis://redis:6379

  db:
    image: postgres:10
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - "3306:3306"
    environment:
      - POSTGRES_DB=development
      - POSTGRES_USER=development
      - POSTGRES_PASSWORD=GdS)FP6*B7zJ

  redis:
    image: redis:latest
    volumes:
      - ./redis-data:/data
    ports:
      - "6379:6379"

volumes:
  prologue-sync:
    external: true
